limetech/dynamix

- plugins/dynamix.docker.manager/createDocker.php
- plugins/dynamix/styles/default-black.css
- plugins/dynamix/styles/default-white.css
Eliminated redundant redundant css/js includes.
> Fixed Create Container page from overriding the theme to white.

- plugins/dynamix.docker.manager/AddContainer.page
- plugins/dynamix.docker.manager/UpdateContainer.page
- plugins/dynamix.docker.manager/createDocker.php
A couple of fixes for some of the issues Jon was noticing yesterday with Docker Manager :neckbeard:
> Docker Manager fixes

- plugins/dynamix.plugin.manager/scripts/plugin
- plugins/dynamix/Confirmations.page
- plugins/dynamix/DiskHealth.page
- plugins/dynamix/ParityCheck.page
- plugins/dynamix/include/DefaultPageLayout.php
- plugins/dynamix/include/DeviceList.php
Not perfect, but at least it shows progress lines in steps of 10%. Have a look and see if it is workable.
I can't get the progress lines to overwrite each other. Somehow including a "&lt;script&gt;" statement breaks the thing, and the approach as done with Docker I can't get it to work (tried hard but alas).
Need other geniuses here :)
> Added progress indicator in file download

- plugins/dynamix/DiskHealth.page
- plugins/dynamix/Notifications.page
- plugins/dynamix/ShareSettings.page
- plugins/dynamix/Syslog.page
- plugins/dynamix/include/DeviceList.php
- plugins/dynamix/include/Download.php
- plugins/dynamix/include/SmartInfo.php
The download function of "Disk Health" and "Syslog" do now a proper cleanup of temporary files.
In addition smartctl is now only invoked when the actual download of disk attributes is requested.
> Improved download function with cleanup

- plugins/dynamix.docker.manager/DockerSettings.page
For consistency with other settings pages.
> Add "Done" button to Docker settings page

- plugins/dynamix.docker.manager/dockerupdate.php
- plugins/dynamix.plugin.manager/Plugins.page
- plugins/dynamix.plugin.manager/include/ShowPlugins.php
- plugins/dynamix/NotificationsArchive.page
- plugins/dynamix/Syslog.page
- plugins/dynamix/scripts/monitor
- plugins/dynamix/scripts/notify
- plugins/dynamix/scripts/plugincheck
Plugins are now displayed with their current status.
I.e. when notification is received for a new plugin version then it can
be installed without doing a manual version check.
Also a "please wait" message is shown prior to building the plugin list.
> Improved plugin manager

- plugins/dynamix.vm.manager/templates/Custom.form.php
> VM Manager last minute tweaks

- plugins/dynamix.vm.manager/AddVM.page
- plugins/dynamix.vm.manager/UpdateVM.page
- plugins/dynamix.vm.manager/VMMachines.page
- plugins/dynamix.vm.manager/classes/libvirt.php
- plugins/dynamix.vm.manager/scripts/dynamix.vm.manager.js
- plugins/dynamix.vm.manager/templates/Custom.form.php
sorry tom, this *should* be the last them :laughing:
> more VM manager help fixes and improvements to page aesthetics

- plugins/dynamix.vm.manager/classes/libvirt.php
> fix libvirt_domain_get_name error on update vm using domain xml

- plugins/dynamix.vm.manager/VMajax.php
- plugins/dynamix.vm.manager/classes/libvirt.php
- plugins/dynamix.vm.manager/templates/Custom.form.php
- fixed bug creating additional disk images when updating a VM
- server-side file checks are performed when picking/typing in a disk image path
> bug fixes and refactoring VM creation code

- plugins/dynamix/NotificationAgents.page
- plugins/dynamix/include/NotificationAgents.xml
Easier selection with dropdown menus, and some more updates to improve consistency.
> Added: dropdown lists in notification agents page

- plugins/dynamix.plugin.manager/Plugins.page
- plugins/dynamix/Notifications.page
- plugins/dynamix/include/Markdown.php
- plugins/dynamix/styles/dynamix-black.css
- plugins/dynamix/styles/dynamix-white.css
Happy Birthday, Ronald!  (closes #63)
> Advanced View toggle for Notifications page

- plugins/dynamix.vm.manager/VMMachines.page
- plugins/dynamix.vm.manager/classes/libvirt.php
- plugins/dynamix.vm.manager/styles/dynamix.vm.manager.css
- Display accurate raw disk size on VMs page instead of 'unknown'
- Allow increasing capacity for raw disk types from VMs page
- CSS fixes on VMs page
> VM Manager: Fix: raw disk size display and adjustment capabilities

- plugins/dynamix/DashStats.page
- plugins/dynamix/include/SystemInformation.php
Tested this on a bunch of systems here and should correct johnodon and others memory reported values.
> Fix: Memory installed and total capacity values

- plugins/dynamix/scripts/monitor
> Replace some awk functions for grep in monitor script

- plugins/dynamix/ArrayOperation.page
got rid off of 'forall' symbol (nobody understood)
> Changed 'awk' to 'grep' for better performance

- plugins/dynamix/Diagnostics.page
Highlights additional items now included in system diagnostics.
> Added description text for under *System*

- plugins/dynamix.vm.manager/VMMachines.page
- plugins/dynamix.vm.manager/templates/OpenELEC.form.php
- VM Manager: ported remaining confirm dialogs to sweetalert.js dialogs
- OpenELEC: added 6.0-beta3 image (beta3 includes hdmi sound fixes for nvidia cards and corrected 'addon_url' to allow plugins in Kodi once again)
- OpenELEC: use readonly for openelec disk image
> VM Manager and OpenELEC Updates

- logging.htm
- plugins/dynamix.docker.manager/include/CreateDocker.php
- plugins/dynamix.docker.manager/log.htm
- update.htm
Eliminates Docker add/update apparent "hangs"
> Remove external resources from progress pages

- plugins/dynamix.apcupsd/UPSsettings.page
- plugins/dynamix/HelpButton.page
- plugins/dynamix/include/DefaultPageLayout.php
- plugins/dynamix/include/ParityHistory.php
Sorry Ronald, the 'help is on/off' splash wasn't a favorite feature among the team here.
> help button tuning and couple other fixes

- plugins/dynamix/include/DashUpdate.php
- plugins/dynamix/include/SystemInformation.php
> Fix: parsing eth speed / duplex (with newer grep)

- plugins/dynamix.plugin.manager/scripts/plugin
also show the reason for the download failure
closes #139, #246
> Fix: plugin script: clean tmp file and exit on failed download

- plugins/dynamix/styles/default-black.css
- plugins/dynamix/styles/default-white.css
Change min width of navbar items.
> Fix website top navbar breaking when multiple plugins installed
